{% set version = "1.1.22" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-biganalytics
  version: {{ version|replace("-", "_") }}

source:
  fn: biganalytics_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/biganalytics_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/biganalytics/biganalytics_{{ version }}.tar.gz
  sha256: d0bf73547cca64479d7e704ad48b3b4d3fba35811e5b74a4c08486911fc93f79

build:
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-biglm
    - r-bigmemory >=4.0.0
    - r-foreach

  run:
    - r-base
    - r-bh
    - r-rcpp
    - r-biglm
    - r-bigmemory >=4.0.0
    - r-foreach

test:
  commands:
    - $R -e "library('biganalytics')"  # [not win]
    - "\"%R%\" -e \"library('biganalytics')\""  # [win]

about:
  home: http://www.bigmemory.org
  license: LGPL-3.0-only OR Apache-2.0
  summary: Extend the 'bigmemory' package with various analytics. Functions 'bigkmeans' and 'binit' may also be used with native R objects. For 'tapply'-like functions, the bigtabulate package may also be helpful. For linear algebra support, see 'bigalgebra'.  For mutex (locking) support for advanced shared-memory usage,
    see 'synchronicity'.
  license_family: LGPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
