travis:
  secure:
    BINSTAR_TOKEN: BVekBggkVAGzj8T++G0YHqGHjRjD9iUwv1EBKkT30j/ccq0eRUOdDmZS9B6K8nv56fLqUcXCNySEupvAx/oA95ny3aUba09nU41JpucgKFneUi9N1MIfyaIKzt4rIn8ZKybB/58fTPRUKzg6yu4ujpA7KtOA14nZs1pBdJA727bAxfdbT/WuDBHxZAtt6qtanmzgXAzUktnSo/+gOekZxapcj06eZ05oIjv71PWdao6IhcyeD3+kNDq+Ufsq2gWOl0HvnLIERIOO9WD+aHgx0m5xP/tg/qoawc0h7l8zUl8mjX2JIoX0tHq97kLp8HiAJV+fNbtZCDhlxfOoZAgBgzODOFlhYp/CcnL99renaTVda6l4/mD9zc6KW+omlRxVwVkc9FJi/gq0/nfIfHB4kcrzsgjng6Fwedq7JaAEURB798ZkKmibtsdRGX4dEBDzQEJSGSRlutQIA9Lgt8WN9bTa1wh4gdz6ljtoVDtCgVlCcStqqm3NWuUOwn9xwmEWPK/9yFtE5KdvswvN++0z41HwtpqR4CKc6LIwsVKXxvGLav2kSY6DxS6MACwXWL417EYy3UE8zHlnJNpy6rMmtqdKRMScNCSRiRHXNnhPfSc6ucs7EtCuw7vdIG9eo45qU3ijzz3vYHZ5ac7QrKuBmBEiooQrwZ+IZKRr8qRMhwg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
