travis:
  secure:
    BINSTAR_TOKEN: Qr2DQja2YqRRLVDg32t15KTiTxZ0ICxlfJhAnWEbA4FHuAvRd/tJuIWEAeD4d4VETsaeEJmhbUQHYrQkVDkD78Y0gOeiD1Ptf71FRKDIqDuozudKdZ8M+cnZWGEKZTGP4f09uNnhKL5zlifihJanzrZcnwWCvG0djUcOwEhegw2tMK82l4zVAMm6XsNVlrNxdwJBO4k24hOVdKDe5yKVRsIUDB0MuUKXnCMPsOOYSk9KDApqjYhe6BUtfNx309P/fHK6wU2iGeI/XphqlP+H2M4s/YDT29cHg50WhsgoTsL6PLjIwxemKkyxA++7Sg0Gqp6YsbOceJNG7VIoY8JAwPeyzelABROhVyAjLR3zOZKh6fAp/ovjWHdKyBY++OROP79QgnaNeZQYr3pljXj4YI8kPffPdz8FW/6gVnn5bmkAZFnLT6nQAL3uQdcdiRxeqlsZTjQYN7yHVJEwoP/IIpBoA5F1gNQ+2Mp4msQbmA7EqFETALOTHz4s0nm49uRBEm59RoXtxq38ZttGV7ICO3i/zikWER2BIBBuJz3VRvY/YpOJpGi4DsfD7z7KxwcMNeaMX9iiiA9/coTKvHhwHPzsacQwvNp5V8kToCNrXLx1LlNRk0VLtvCONAAzeuyORAYA9FtTcB1bqnl6MDy+LmcRn1imj6OnQuWQ0XH2yf4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
