travis:
  secure:
    BINSTAR_TOKEN: XD37yrKgUztpbd2c6WbjrPd1ErAbYJ4Pa/bFFqzvhwm/uqWpXeUsZSKCD2dZWQ93s3QnQZw6NRQYOjXw9qabjWp9fEWS/0shsCtsIWce7/qMRZEWDDohxBb3Xy1M2npqVOzCW7JuEP0qVy0ct+l5ltupdqa08unYr0u3IPljyiaolCVPqeGEn4lxeO5Y0BIl9Jyl7LhzrEpl8P+8WjO3JQOzIaicjJwB+UlYv+bH2GVMKVx8l9DuKfrQYDoChnLCRfaejL2xOT/jcdFVRctUm9rALrmBxoh4vgujgeqa5QLOQwTr4NAqbKrI6b3+tDXl/Bv00MqfaUK0ZUsm1Beaoyy7mx0QCN8o3+UJJw7pZ2U2hbLBamTo4NNyx6wLj8XxtLMnL8H2+BhDtgTkb2uStlrfMzqUwSAmtyAAe6aUyD0Adyf9rfHrsTS9SipHqBIkfcaEygqNA9o5WEFYBrJ1ESP7/LXmoqhpklbFbEeWt1VXvGa4m64Bw/X09GRIHmbKwiEFqcjpgcVdZZm5tO3yQVrAoidvWIOAU5de7DrXSgOQPOJB3dDXUH2KQMmOnygXSJWS0mtladC69TLYJpCJK6yq8dOT/GNSxKt64LCOcSZgC0s/TF9+pVzOdRZ/HZyhZCAW0ImcQ+TS8Ew02qEi8x/IvIRA+jv8TZgI1PGcz44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
