appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WANwf9CfgQaJH3Dg5iyimhnukBvsZVa5u/D6BP8WYeOYUQfAkPmAVH3J3jVzdEl80X5ATVeIDvhu4QunS/P2m+wITbt+nMITNk0ahTd2u1FNR655FZPNfJj54OqOkv3AZEuMVMUHz61nlLS7nSQHHP8WIm+A7P/UdespXU9MVJLiu9EE3hRO9z7qNEaywdrLSMcFRXrZ4z7y5QHgj1a94inTppvFW8na2+8r2Ab8GAJZ6lbLljgFr5yxvNFxVCnPJy+KCuI2VJSPclX9MLNWOOauSmV3oDx/gfGJfGXdbfyLZaN3kpP2mP+SAQKyRKRM2Jx1slYjHqpIKow00bAiF8cc8YGC6/jmQyN01AUwgT6c4LycMD6L5muU/oS/E8Oc3PwX146oHbnTbIFACs4DOJAcswP4FUfBN6JyCd9SZnBfjXU/4HXrjUNfj6xXdzuwhjez+Rs0iX0P7vXXxP5bzvXhUIcebjssqRGx3ce47b6kQqx0jZ36PO3SOIC6tncRC05DIdGZj4mMQkXCxkQ/OXXGAl109GuC5Vrn15Aqf+Wgnhmgd2PooBChVUqa4VTLWC8aKTNjQCEJtUfnnZrMr7bwELSzWD65wtozsCUNRV81zc6UJQWsOtwhn9oDXhk9snBIeFoUYzD0UemPmnZB5bJGjTi4OywtzRqCVqxPhS0=}
