travis:
  secure:
    BINSTAR_TOKEN: UQ0m0BVTiTngA5T6u2R0SIt9hU3kaJm5FQn0L7ClcqSKjS6s8SzNH92c00rHTxqivkHwSAAybFmNI4wUQc4EQnrN3QOmZ+0txoppCCP2/Mr5JDkkT0uGgH+NkbXMD8znpla4ZQb9F9mPm1kRb1DvcQF9X11iAtPQ2aHRRqydjYN06gKc/gXxO6g2I1CW1aPTDGUk77sin5kRnNOycYhM8Xt5cB+OZFjjumfjU3SjX5QsmkPGIEBL1fwGZzjZ50yiUutUyaJMpWFoY73NlgaClZdeEg08ajE+uPRnMzQTY2O2xBrLpn6N9tvYAuDFKfciqqPZlAj9uyCXGKHSmthPeVV/TDEmC7R7Ypsjx+BM5dNDpxqtoPgrqsrAQMB+74AGpaf9krqRHnINQGsCEhwMB/aGXd84v0W7RvRRxK+gcTvKjZ/ROzAjW7b7loItTH2JIAEjdlNd6aD8KW6QLs8TKNmfMUuRi0CbtC+sA1gLRbFxbMuTfRT+7Jbxn7S4rmyFofwCONCta5V8vTHaB8RH3V1CzyHgl8qgiz9a1Hl577IJy2BeTKan7t5tkZ/lVoA7b9q4USvFJDMz2gFnZyh9XVdVK4HCECOsT04yDTTua7uFlx69lPbbxHR+ravHKYBxz1lJkjC4KnyxOv0vjCWGnI338WmAfgbbVv5zJVljOkg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
