travis:
  secure:
    BINSTAR_TOKEN: Db2vB4fwcNnrH8mVv/zyYmLOQFl+K0plQDcq2aRIphJGshK0l05h+2hesWZRkxt2cOekA7fV4jFhuGo/2WNo05g/ghI8u7HWDEt8OKhE/rGV4Tak4P7zqGkgcJqrgrTL6dAuH5nngqU5scswfqzWAy4X6q4ud90Ci8zBB5UCNGTNtiFDA+oq6u5MNf281wldGamagWOKEv4/UEzARI3VddGSPVM5EoBMQYXO/IT+7gv5prIlCUSyisqHu7fULXS4KNinluGoet22KYUQ9VWsRCdTcqnRaDZ1gCw9aGu9fdgG3Nghdf3Kb/KSz4ktYm4ZghfIr1Y+CZE7odS5Ni2je8HK43JPvWMemaWZNcEZL+5XVZF+Vn6cq35CKMvTtu/QiJoVbyirLToMgs6hUT/UuJi8eQgnm/lP8LpDy7+apkls8TDLRFYHiVwFEu/D+0G92icnX5kGDQNm/J5bQoqCmhvA2amiXltMraqteeD0FWBQde0SEwn8qkl0A2Cj3Xgv4Jz/1TnaEyEmjtOWDMz1fTqVck//NuU4jvcQWAVM91uFenAOdR6qcg6pglLMhLncMTPZXP+9G21Ie0kFmGPZnrcNRYC1ygLmnsQbHYDVjqsYpVP/EAQr+8WfxwK/0TDQRphV/CZacwDbG79L645qwQ1GDTtFJgvUDFBSIJEjWN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
